server:
  port: 8082
  tomcat:
    max-http-form-post-size: 2MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mywebsite
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 333333


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: top.cuizilin.website.pojo
  configuration:
    map-underscore-to-camel-case: true

front-end-url: http://localhost:8080
redis-host: localhost